#include <atomic>
#include <bit>
#include <cctype>
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <mutex>
#include <string>
#include <thread>
#include <rex/cvar.h>
#include <rex/logging/macros.h>
#include <rex/ppc.h>
#include <rex/runtime.h>
#include <rex/system/flags.h>
#include <rex/ui/overlay/debug_overlay.h>
#include <generated/re_cherry_config.h>
#include <generated/re_cherry_init.h>

#ifdef _WIN32
#include <immintrin.h>
#include <timeapi.h>
#endif

REXCVAR_DEFINE_BOOL(fps, false, "Lollipop/Cheats", "fps");
REXCVAR_DEFINE_BOOL(disable_xbox_live_prompt, true, "Lollipop/Patches",
                    "Auto-dismiss Xbox Live connection prompts");
REXCVAR_DEFINE_BOOL(force_dlc_costumes, true, "Lollipop/Patches",
                    "Force DLC costume licenses on");

static std::atomic<uint64_t> g_guest_frame_count{0};

#ifdef _WIN32
static std::once_flag g_timer_init;

static void EnableHighResTimer() {
    std::call_once(g_timer_init, [] {
        timeBeginPeriod(1);
        REXLOG_INFO("[threading] high-res timer enabled");
    });
}

void DisableHighResTimer() {
    timeEndPeriod(1);
    REXLOG_INFO("[threading] high-res timer disabled");
}

static ppc_u32_result_t Sleep_hook(ppc_u32_t ms_val) {
    const uint32_t ms = ms_val;
    EnableHighResTimer();

    if (ms == 0) {
        SwitchToThread();
        return 0;
    }

    const auto target = std::chrono::steady_clock::now()
                      + std::chrono::milliseconds(ms);

    if (ms >= 2) {
        std::this_thread::sleep_for(
            std::chrono::milliseconds(ms) - std::chrono::microseconds(1500));
    } else {
        ::Sleep(1);
    }

    while (std::chrono::steady_clock::now() < target)
        _mm_pause();

    return 0;
}
PPC_HOOK(rex_Sleep, Sleep_hook);
#endif

namespace {

constexpr uint32_t kForcedDlcLicenseMask = 0xFFFFFFFFu;

std::string read_guest_utf16_ascii(uint8_t* base, uint32_t guest_ptr) {
    if (!guest_ptr) {
        return {};
    }
    std::string out;
    out.reserve(128);
    for (size_t i = 0; i < 256; ++i) {
        uint16_t ch = PPC_LOAD_U16(guest_ptr + static_cast<uint32_t>(i * 2));
        if (ch == 0) {
            break;
        }
        out.push_back(ch <= 0x7F ? static_cast<char>(ch) : '?');
    }
    return out;
}

std::string ascii_lower(std::string text) {
    for (char& ch : text) {
        ch = static_cast<char>(std::tolower(static_cast<unsigned char>(ch)));
    }
    return text;
}

bool is_xbox_live_prompt(const std::string& title, const std::string& text) {
    const std::string haystack = ascii_lower(title + "\n" + text);
    return haystack.find("xbox live") != std::string::npos ||
           haystack.find("connect to xbox live") != std::string::npos ||
           haystack.find("connect to xbox") != std::string::npos ||
           haystack.find("sign in to xbox live") != std::string::npos ||
           haystack.find("xboxlive") != std::string::npos;
}

}  // namespace

static float read_engine_delta_time() {
    auto* rt = rex::Runtime::instance();
    if (!rt) return 0.0f;
    uint8_t* base = rt->virtual_membase();
    if (!base) return 0.0f;
    uint32_t raw = __builtin_bswap32(*(volatile uint32_t*)(base + 0x83354AF0u));
    return std::bit_cast<float>(raw);
}

rex::ui::FrameStats GetGuestFrameStats() {
    float dt = read_engine_delta_time();
    double fps_val = (dt > 0.001f) ? 1.0 / dt : 0.0;
    return {dt * 1000.0, fps_val, g_guest_frame_count.load(std::memory_order_relaxed)};
}

// Link stub for the fps midasm hook (address 0x8253A7D0 inside sub_8253A7C0).
// sub_8253A7C0 is fully overridden via PPC_FUNC_IMPL below so this is dead.
void fps(PPCRegister&) {}

// fps1: midasm hook at 0x829EAA08 (li r11, 2) inside the GPU Present path,
// fired AFTER the instruction so r11 = 2 (vsync every other vblank = 30 fps).
// When fps uncap is on, zero out r11 → present interval 0 (immediate / no cap).
void fps1(PPCRegister& r11) {
    if (REXCVAR_GET(fps)) {
        r11.u32 = 0;
    }
}

// fps2: midasm hook at 0x824A1EF0 (li r11, 2) inside the loading/secondary
// GPU Present path (sub_824A1AE0). Same cap mechanism as fps1.
void fps2(PPCRegister& r11) {
    if (REXCVAR_GET(fps)) {
        r11.u32 = 0;
    }
}

// Overrides the weak-linked sub_8253A7C0 generated by the recompiler.
//
// Original logic: loads a global flag from [r9+932]. If zero, returns f1 from
// [r8+44] (uncapped delta). If non-zero, loads f1 from [r3+0x4B8] (the 60fps
// cap value) — this is what the Xenia patch NOPs at 0x8253A7E0.
//
// We always take the uncapped path when the fps CVar is enabled, and count
// guest frames here since this function is called once per frame.
PPC_FUNC_IMPL(sub_8253A7C0) {
    PPC_FUNC_PROLOGUE();
    g_guest_frame_count.fetch_add(1, std::memory_order_relaxed);

    const uint32_t r9 = uint32_t(int32_t(-2093547520) + int32_t(-27952));
    const uint32_t r8 = uint32_t(int32_t(-2113404928) + int32_t(7664));

    PPCRegister temp{};
    ctx.fpscr.disableFlushMode();
    temp.u32 = PPC_LOAD_U32(r8 + 44);
    ctx.f1.f64 = double(temp.f32);

    if (!REXCVAR_GET(fps)) {
        // Original: conditionally load the 60fps cap into f1
        if (PPC_LOAD_U32(r9 + 932) != 0) {
            temp.u32 = PPC_LOAD_U32(ctx.r3.u32 + 1208);
            ctx.f1.f64 = double(temp.f32);
        }
    }
    // fps enabled: return with uncapped f1 from [r8+44]
}

extern "C" void sub_82BF4288(PPCContext& ctx, uint8_t* membase) {
    uint8_t* base = membase;
    uint32_t ea{};
    const uint32_t saved_sp = ctx.r1.u32;
    const uint32_t title_ptr = ctx.r4.u32;
    const uint32_t text_ptr = ctx.r5.u32;

    ctx.r12.u64 = ctx.lr;
    PPC_STORE_U32(saved_sp - 8, ctx.r12.u32);
    ea = saved_sp - 96;
    PPC_STORE_U32(ea, saved_sp);
    ctx.r1.u32 = ea;

    const uint32_t overlapped_ptr = PPC_LOAD_U32(ctx.r1.u32 + 180);
    PPC_STORE_U32(ctx.r1.u32 + 84, overlapped_ptr);

    if (REXCVAR_GET(disable_xbox_live_prompt)) {
        const std::string title = read_guest_utf16_ascii(base, title_ptr);
        const std::string text = read_guest_utf16_ascii(base, text_ptr);
        if (is_xbox_live_prompt(title, text)) {
            const bool old_headless = REXCVAR_GET(headless);
            const uint32_t old_active_button = ctx.r8.u32;
            REXCVAR_SET(headless, true);
            if (ctx.r6.u32 >= 2) {
                ctx.r8.u32 = 1;
            }
            ctx.lr = 0x82BF42A0;
            __imp__XamShowMessageBoxUI(ctx, base);
            ctx.r8.u32 = old_active_button;
            REXCVAR_SET(headless, old_headless);
            ctx.r1.u32 = saved_sp;
            ctx.r12.u64 = PPC_LOAD_U32(ctx.r1.u32 - 8);
            ctx.lr = ctx.r12.u64;
            return;
        }
    }

    ctx.lr = 0x82BF42A0;
    if (auto* rt = rex::Runtime::instance()) {
        __imp__XamShowMessageBoxUI(ctx, rt->virtual_membase());
    }
    ctx.r1.u32 = saved_sp;
    ctx.r12.u64 = PPC_LOAD_U32(ctx.r1.u32 - 8);
    ctx.lr = ctx.r12.u64;
}

extern "C" void sub_82BF3EC0(PPCContext& ctx, uint8_t* membase) {
    uint8_t* base = membase;
    __imp__XamContentGetLicenseMask(ctx, base);
    if (!REXCVAR_GET(force_dlc_costumes)) {
        return;
    }
    if (ctx.r3.u32 == 0 && ctx.r3.s32 == 0 && ctx.r4.u32) {
        PPC_STORE_U32(ctx.r4.u32, kForcedDlcLicenseMask);
    }
}

// sub_822E7DA0: per-frame FPS histogram stats collector.
// Bins frame times into debug telemetry buckets (5–60+ fps) and logs spikes.
// Only ever referenced via a function-pointer table; output is never displayed
// on PC. Making it a no-op removes one mftb read + ~60 branch comparisons
// per frame with zero gameplay impact.
PPC_FUNC_IMPL(sub_822E7DA0) {
    PPC_FUNC_PROLOGUE();
}

extern "C" void sub_82BF3E20(PPCContext& ctx, uint8_t* membase) {
    uint8_t* base = membase;
    __imp__XamContentCreateEx(ctx, base);
    if (!REXCVAR_GET(force_dlc_costumes)) {
        return;
    }
    if (ctx.r3.u32 == 0 && ctx.r8.u32) {
        PPC_STORE_U32(ctx.r8.u32, kForcedDlcLicenseMask);
    }
}
